export const commodities = [
    "Tomato Big(Nepali)",
    "Tomato Big(Indian)",
    "Tomato Small(Local)",
    "Tomato Small(Tunnel)",
    "Potato Red",
    "Potato Red(Indian)",
    "Potato Red(Mude)",
    "Onion Dry (Indian)",
    "Carrot(Local)",
    "Carrot(Terai)",
    "Cabbage(Local)",
    "Cauli Local",
    "Raddish White(Local)",
    "Raddish White(Hybrid)",
    "Brinjal Long",
    "Brinjal Round",
    "Cow pea(Long)",
    "Cowpea(Short)",
    "Green Peas",
    "French Bean(Local)",
    "French Bean(Hybrid)",
    "French Bean(Rajma)",
    "Soyabean Green",
    "Bitter Gourd",
    "Bottle Gourd",
    "Pointed Gourd(Local)",
    "Pointed Gourd(Terai)",
    "Snake Gourd",
    "Smooth Gourd",
    "Sponge Gourd",
    "Pumpkin",
    "Squash(Long)",
    "Squash(Round)",
    "Okara",
    "Sweet Potato",
    "Arum",
    "Christophine",
    "Brd Leaf Mustard",
    "Spinach Leaf",
    "Mustard Leaf",
    "Mushroom(Kanya)",
    "Mushroom(Button)",
    "Asparagus",
    "Neuro",
    "Brocauli",
    "Sugarbeet",
    "Red Cabbbage",
    "Lettuce",
    "Knolkhol",
    "Celery",
    "Fennel Leaf",
    "Mint",
    "Turnip A",
    "Tamarind",
    "Bamboo Shoot",
    "Tofu",
    "Gundruk",
    "Apple(Jholey)",
    "Apple(Fuji)",
    "Banana",
    "Lime",
    "Pomegranate",
    "Mango(Maldah)",
    "Mango(Dushari)",
    "Grapes(Green)",
    "Grapes(Black)",
    "Water Melon(Green)",
    "Sweet Orange",
    "Mandarin",
    "Pineapple",
    "Cucumber(Local)",
    "Cucumber(Hybrid)",
    "Jack Fruit",
    "Papaya(Indian)",
    "Litchi(Local)",
    "Litchi(Indian)",
    "Ginger",
    "Chilli Dry",
    "Chilli Green",
    "Chilli Green(Bullet)",
    "Chilli Green(Machhe)",
    "Chilli Green(Akbare)",
    "Capsicum",
    "Coriander Green",
    "Garlic Dry Chinese",
    "Garlic Dry Nepali",
    "Clive Dry",
    "Clive Green",
    "Fish Fresh(Rahu)",
    "Fish Fresh(Bachuwa)",
    "Fish Fresh(Chhadi)",
    "King Oyster",
    "Lentinula Edodes"
]
