import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import TopNavbar from "@/components/TopNavbar";
import { AppContextProvider } from "@/context/appContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Visualized Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased box-border h-screen flex`}>

        <AppContextProvider>

          <Sidebar />

          <main className="h-full flex-1 flex flex-col">
            <TopNavbar />
            <div className="flex-1 px-6 overflow-auto">
              {children}
            </div>
          </main>

        </AppContextProvider>

      </body>
    </html>
  );
}
